# 1 つのテストケースを実行して結果を比較する（CTest から cmake -P で呼ばれる）
#   -DPROGRAM=実行ファイル -DPROJECT_DIR=プロジェクトフォルダ -DCASE=ケース名 -DWORK_DIR=作業フォルダ
# 仕様はルートの CMakeLists.txt の softprac_add_tests の説明を参照
cmake_minimum_required(VERSION 3.21)

foreach(var PROGRAM PROJECT_DIR CASE WORK_DIR)
  if(NOT DEFINED ${var})
    message(FATAL_ERROR "${var} が指定されていません")
  endif()
endforeach()

set(prefix "${PROJECT_DIR}/tests/${CASE}")

# 作業フォルダを作り直し，プロジェクトフォルダのデータファイル（ソース以外）をコピーする
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")
file(GLOB data_files LIST_DIRECTORIES false "${PROJECT_DIR}/*")
foreach(f IN LISTS data_files)
  get_filename_component(fname "${f}" NAME)
  if(NOT fname MATCHES "(\\.c|\\.h|^CMakeLists\\.txt|^README.*)$")
    file(COPY "${f}" DESTINATION "${WORK_DIR}")
  endif()
endforeach()
# ケース専用のファイル（<ケース>.setup/ 以下）も作業フォルダへコピーする
if(IS_DIRECTORY "${prefix}.setup")
  file(GLOB setup_files LIST_DIRECTORIES true "${prefix}.setup/*")
  file(COPY ${setup_files} DESTINATION "${WORK_DIR}")
endif()

# 引数（1 行 1 引数，空行は空文字列）。空の引数も渡せるように bracket 引数で組み立てる
set(command_code "execute_process(COMMAND [==[${PROGRAM}]==]")
if(EXISTS "${prefix}.args")
  file(READ "${prefix}.args" args_text)
  if(NOT args_text STREQUAL "")
    string(REPLACE "\r" "" args_text "${args_text}")
    string(REGEX REPLACE "\n$" "" args_text "${args_text}")
    if(args_text STREQUAL "")
      # 空行 1 行だけのファイル = 空文字列の引数 1 つ
      string(APPEND command_code " [==[]==]")
    else()
      string(REPLACE ";" "\\;" args_text "${args_text}")
      string(REPLACE "\n" ";" args_list "${args_text}")
      foreach(a IN LISTS args_list)
        string(APPEND command_code " [==[${a}]==]")
      endforeach()
    endif()
  endif()
endif()
string(APPEND command_code "\n  WORKING_DIRECTORY [==[${WORK_DIR}]==]")
if(EXISTS "${prefix}.in")
  string(APPEND command_code "\n  INPUT_FILE [==[${prefix}.in]==]")
endif()
string(APPEND command_code "\n  OUTPUT_VARIABLE actual_out\n  ERROR_VARIABLE actual_err\n  RESULT_VARIABLE actual_code\n  TIMEOUT 20)")
cmake_language(EVAL CODE "${command_code}")

set(failed FALSE)

function(normalize var)
  string(REPLACE "\r\n" "\n" v "${${var}}")
  set(${var} "${v}" PARENT_SCOPE)
endfunction()

# 終了コード
set(expected_code 0)
if(EXISTS "${prefix}.code")
  file(STRINGS "${prefix}.code" expected_code LIMIT_COUNT 1)
  string(STRIP "${expected_code}" expected_code)
endif()
if(NOT "${actual_code}" STREQUAL "${expected_code}")
  message("[NG] 終了コード: 期待 ${expected_code}，実際 ${actual_code}")
  set(failed TRUE)
endif()

# 標準出力
file(READ "${prefix}.out" expected_out)
normalize(expected_out)
normalize(actual_out)
if(NOT actual_out STREQUAL expected_out)
  message("[NG] 標準出力が一致しません\n----- 期待 -----\n${expected_out}----- 実際 -----\n${actual_out}----------------")
  set(failed TRUE)
endif()

# 標準エラー出力（任意）
if(EXISTS "${prefix}.err")
  file(READ "${prefix}.err" expected_err)
  normalize(expected_err)
  normalize(actual_err)
  if(NOT actual_err STREQUAL expected_err)
    message("[NG] 標準エラー出力が一致しません\n----- 期待 -----\n${expected_err}----- 実際 -----\n${actual_err}----------------")
    set(failed TRUE)
  endif()
endif()

# 実行後のファイル（.bin はバイト単位，それ以外は改行コードを無視して比較）
if(IS_DIRECTORY "${prefix}.files")
  file(GLOB_RECURSE expected_files RELATIVE "${prefix}.files" "${prefix}.files/*")
  foreach(rel IN LISTS expected_files)
    set(actual_path "${WORK_DIR}/${rel}")
    if(NOT EXISTS "${actual_path}")
      message("[NG] ファイル ${rel} が作られていません")
      set(failed TRUE)
      continue()
    endif()
    if(rel MATCHES "\\.bin$")
      file(SHA256 "${prefix}.files/${rel}" h1)
      file(SHA256 "${actual_path}" h2)
      if(NOT h1 STREQUAL h2)
        file(READ "${actual_path}" hex HEX)
        message("[NG] ファイル ${rel} の内容が一致しません（実際: ${hex}）")
        set(failed TRUE)
      endif()
    else()
      file(READ "${prefix}.files/${rel}" e)
      file(READ "${actual_path}" a)
      normalize(e)
      normalize(a)
      if(NOT a STREQUAL e)
        message("[NG] ファイル ${rel} の内容が一致しません\n----- 期待 -----\n${e}----- 実際 -----\n${a}----------------")
        set(failed TRUE)
      endif()
    endif()
  endforeach()
endif()

if(failed)
  if(NOT actual_err STREQUAL "")
    message("----- 標準エラー出力 -----\n${actual_err}")
  endif()
  message(FATAL_ERROR "テスト ${CASE} に失敗しました")
endif()
